# nixpacks.toml
[phases.setup]
nixPkgs = [
  "python312",     
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "harfbuzz",
  "freetype",
  "fontconfig",
  "pkg-config"
]

# (اختياري) خطوط محسّنة، مفيد لو عندك عربي
# nixPkgs = [..., "noto-fonts", "noto-fonts-cjk", "noto-fonts-emoji"]
