# Generated by Django 5.2.4 on 2025-08-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_product_suppliers_supplierproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="inventory.SupplierProduct",
                to="inventory.supplier",
            ),
        ),
    ]
