# Generated by Django 5.2.4 on 2025-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_product_suppliers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="batch_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dosage_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tablet", "Tablet"),
                    ("capsule", "Capsule"),
                    ("syrup", "Syrup"),
                    ("injection", "Injection"),
                    ("ointment", "Ointment"),
                    ("cream", "Cream"),
                    ("drops", "Drops"),
                    ("spray", "Spray"),
                    ("gel", "Gel"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="strength",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
